spring.application.name=SecurityApplication
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/security-app
spring.datasource.username=root
spring.datasource.password=Abc@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##security configs
#spring.security.user.name=Ankita
#spring.security.user.password=Abc@123


#JWT token
jwt.secretKey=wertyuikjhgf34567uhgfdfghjio98765rfvgbnfghjkjhgfr567uikjnbvfdr567ujhbvfrt67uj